//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackReply
    {
        public int FRID { get; set; }
        public Nullable<System.DateTime> FRTime { get; set; }
        public string FRContent { get; set; }
        public Nullable<int> MGID { get; set; }
        public Nullable<int> FBID { get; set; }
    
        public virtual Feedback Feedback { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
