//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NID { get; set; }
        public System.DateTime NTime { get; set; }
        public string NTitle { get; set; }
        public string NContent { get; set; }
        public string NAbstract { get; set; }
        public string NImage { get; set; }
        public Nullable<int> NCID { get; set; }
        public string NViewnum { get; set; }
        public string NCommentnum { get; set; }
        public Nullable<int> VID { get; set; }
    
        public virtual NewsComment NewsComment { get; set; }
        public virtual Video Video { get; set; }
    }
}
