//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int PID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string PTitle { get; set; }
        public Nullable<System.DateTime> PTime { get; set; }
        public string PContent { get; set; }
        public string PViewnum { get; set; }
        public Nullable<int> VID { get; set; }
        public Nullable<int> PCID { get; set; }
        public string PCommentnum { get; set; }
        public string UserName { get; set; }
    
        public virtual PostsComment PostsComment { get; set; }
        public virtual Users Users { get; set; }
        public virtual Video Video { get; set; }
    }
}
